name: "htm-backend-api-proxy"
services:
  nginx:
    image: nginx:1.29.3
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/upstream_vars.conf:/etc/nginx/upstream_vars.conf:ro
    ports:
      - ${EXPOSED_PORT:-18000}:80
